name: "Jerry Chee"
output_dir: "."
navbar:
  title: "Jerry Chee"
  left:
    - text: "Career"
      href: career.html
  right:
    - icon: fa-envelope fa-lg
      href: contact.html
    - icon: fa-github fa-lg
      href: https://google.com.sg
    - icon: fa-linkedin fa-lg
      href: https://www.linkedin.com/jerrychee
output:
  html_document:
    css: 'styles.css'
    remote_theme: thelehhman/texture
